In [1]:
#Browsing indi table in DB for potential appendiceal cancer analyses.

import sqlite3
import pandas as pd
from pathlib import Path

project_root = Path.cwd().parents[0]
db_path = project_root / "database" / "faers.db"
conn = sqlite3.connect(db_path)

indi = pd.read_sql_query("SELECT * FROM indi LIMIT 10000", conn)

In [ ]:
print(indi.shape)
print(indi.dtypes)

primaryid         int64
caseid            int64
indi_drug_seq     int64
indi_pt             str
source_quarter      str
dtype: object

In [ ]:
indi.isnull().sum()

primaryid         0
caseid            0
indi_drug_seq     0
indi_pt           0
source_quarter    0
dtype: int64

In [5]:
indi.nunique()

primaryid         1322
caseid            1322
indi_drug_seq      592
indi_pt            570
source_quarter       1
dtype: int64

In [6]:
indi['indi_pt'].value_counts().head(20)

indi_pt
Product used for unknown indication         4746
Rheumatoid arthritis                         948
Attention deficit hyperactivity disorder     151
Asthma                                       129
Hypertension                                 123
Pain                                         106
HIV infection                                101
Autism spectrum disorder                      93
Bipolar disorder                              93
Narcolepsy                                    82
Schizophrenia                                 79
Depression                                    77
Prophylaxis                                   72
Oppositional defiant disorder                 64
Cataplexy                                     64
Coronary artery disease                       64
Juvenile idiopathic arthritis                 62
Affective disorder                            60
Parkinson's disease                           53
Sleep disorder                                50
Name: count, dtype: int64

In [12]:
cancer_indi_counts = pd.read_sql_query("""
SELECT indi_pt, COUNT(*) AS reports
FROM indi
WHERE indi_pt LIKE '%appendic%'
   OR indi_pt LIKE '%colorect%'
   OR indi_pt LIKE '%periton%'
   OR indi_pt LIKE '%pseudomyxoma%'
   OR indi_pt LIKE '%cecal%'
   OR indi_pt LIKE '%mucinous%'
   OR indi_pt LIKE '%colon cancer%'
GROUP BY indi_pt
ORDER BY reports DESC
""", conn)

cancer_indi_counts

                                indi_pt  reports
0                          Colon cancer     6647
1          Colorectal cancer metastatic     5273
2                     Colorectal cancer     3094
3               Colon cancer metastatic     1236
4         Malignant peritoneal neoplasm      736
..                                  ...      ...
66             Complicated appendicitis        2
67  Borderline mucinous tumour of ovary        2
68                    Peritoneal lavage        1
69            Appendicitis noninfective        1
70        Appendiceal mucinous neoplasm        1

[71 rows x 2 columns]

In [14]:
print(cancer_indi_counts.to_string())

                                                   indi_pt  reports
0                                             Colon cancer     6647
1                             Colorectal cancer metastatic     5273
2                                        Colorectal cancer     3094
3                                  Colon cancer metastatic     1236
4                            Malignant peritoneal neoplasm      736
5                                 Metastases to peritoneum      605
6                                      Peritoneal dialysis      575
7                                Colorectal adenocarcinoma      460
8                                              Peritonitis      358
9                                    Colon cancer stage IV      310
10                             Colorectal cancer stage III      234
11                                  Colon cancer stage III      171
12                                   Peritonitis bacterial      138
13                         HER2 positive colorectal cancer      127
14                              Colorectal cancer stage IV      127
15                                  Retroperitoneal cancer      125
16                       Peritoneal mesothelioma malignant      107
17                                            Appendicitis      100
18                                Retroperitoneal fibrosis       65
19                                   Colon cancer stage II       53
20                                          Appendicectomy       41
21                               Mucinous breast carcinoma       38
22                                  Colon cancer recurrent       38
23                                 Appendicitis perforated       38
24     Hereditary non-polyposis colorectal cancer syndrome       37
25                       Spontaneous bacterial peritonitis       36
26                                 Peritoneal cancer index       36
27                              Colorectal cancer stage II       31
28                                      Colorectal adenoma       28
29                           Metastases to retroperitoneum       26
30                                   Peritonsillar abscess       22
31                               Mycobacterial peritonitis       22
32                                     Colorectal neoplasm       22
33                                      Peritoneal sarcoma       21
34                             Colorectal cancer recurrent       20
35                                Retroperitoneal neoplasm       19
36                         Retroperitoneal lymphadenopathy       19
37                                 Peritoneal tuberculosis       17
38                                     Peritoneal neoplasm       14
39                     Mucinous adenocarcinoma of appendix       14
40                         Peritoneal carcinoma metastatic       10
41                                 Escherichia peritonitis       10
42                                     Peritoneal disorder        9
43                       Mucinous cystadenocarcinoma ovary        9
44                                  Pseudomyxoma peritonei        8
45                               Retroperitoneal haematoma        7
46                      Encapsulating peritoneal sclerosis        7
47                     Retroperitoneal neoplasm metastatic        6
48                                 Retroperitoneal abscess        6
49             Peritoneal mesothelioma malignant recurrent        6
50                                      Peritoneal abscess        6
51                 Intraductal papillary mucinous neoplasm        6
52                                      Fungal peritonitis        6
53                               Colorectal cancer stage I        6
54                                        Pneumoperitoneum        5
55                                      Stump appendicitis        4
56                       Peritoneal permeability decreased        4
57                                         Haemoperitoneum        4
58                                       Focal peritonitis        4
59                                  Peritoneal gliomatosis        3
60                                    Colon cancer stage I        3
61                             Ventriculo-peritoneal shunt        2
62                                    Retroperitoneum cyst        2
63  Recurrent N-ras mutation-positive colorectal carcinoma        2
64                                         Peritonsillitis        2
65    Intraductal papillary-mucinous carcinoma of pancreas        2
66                                Complicated appendicitis        2
67                     Borderline mucinous tumour of ovary        2
68                                       Peritoneal lavage        1
69                               Appendicitis noninfective        1
70                           Appendiceal mucinous neoplasm        1

In [17]:
cancer_terms = [
    'Colon cancer',
    'Colorectal cancer metastatic',
    'Colorectal cancer',
    'Colon cancer metastatic',
    'Malignant peritoneal neoplasm',
    'Metastases to peritoneum',
    'Colorectal adenocarcinoma',
    'Colon cancer stage IV',
    'Colorectal cancer stage III',
    'Colon cancer stage III',
    'HER2 positive colorectal cancer',
    'Colorectal cancer stage IV',
    'Peritoneal mesothelioma malignant',
    'Colon cancer stage II',
    'Colon cancer recurrent',
    'Colorectal cancer stage II',
    'Colorectal neoplasm',
    'Peritoneal sarcoma',
    'Colorectal cancer recurrent',
    'Peritoneal neoplasm',
    'Mucinous adenocarcinoma of appendix',
    'Peritoneal carcinoma metastatic',
    'Pseudomyxoma peritonei',
    'Peritoneal mesothelioma malignant recurrent',
    'Intraductal papillary mucinous neoplasm',
    'Colorectal cancer stage I',
    'Colon cancer stage I',
    'Appendiceal mucinous neoplasm',
    'Hereditary non-polyposis colorectal cancer syndrome',
]

cancer_drugs = pd.read_sql_query(f"""
SELECT 
    d.drugname,
    COUNT(DISTINCT d.primaryid) AS reports
FROM drug d
JOIN indi i ON d.primaryid = i.primaryid
WHERE i.indi_pt IN ({','.join(['?' for _ in cancer_terms])})
GROUP BY d.drugname
ORDER BY reports DESC
LIMIT 30
""", conn, params=cancer_terms)

cancer_drugs

                    drugname  reports
0                OXALIPLATIN     1954
1               FLUOROURACIL     1844
2                BEVACIZUMAB     1015
3                 LEUCOVORIN      884
4               CAPECITABINE      875
5               FRUQUINTINIB      673
6                 IRINOTECAN      614
7                    LONSURF      567
8                   VECTIBIX      563
9                  CETUXIMAB      466
10        LEUCOVORIN CALCIUM      438
11                  BRAFTOVI      416
12  IRINOTECAN HYDROCHLORIDE      382
13                   AVASTIN      351
14                   ERBITUX      341
15               ONDANSETRON      254
16             DEXAMETHASONE      251
17                    ZEJULA      233
18                  STIVARGA      220
19               PANITUMUMAB      194
20                  KEYTRUDA      172
21             ACETAMINOPHEN      166
22    LEVOLEUCOVORIN CALCIUM      164
23                AMLODIPINE      156
24                   ELIQUIS      149
25                   ASPIRIN      146
26                   MEKTOVI      144
27           SODIUM CHLORIDE      137
28                LOPERAMIDE      130
29              ATORVASTATIN      127

In [15]:
reaction_counts = pd.read_sql_query("""
SELECT
    i.indi_pt,
    r.pt AS reaction,
    COUNT(DISTINCT r.primaryid) AS reports
FROM indi i
JOIN reac r ON i.primaryid = r.primaryid
WHERE i.indi_pt IN (
    'Colon cancer',
    'Colorectal cancer',
    'Colorectal cancer metastatic',
    'Colon cancer metastatic',
    'Malignant peritoneal neoplasm',
    'Pseudomyxoma peritonei',
    'Mucinous adenocarcinoma of appendix'
)
GROUP BY i.indi_pt, r.pt
ORDER BY i.indi_pt, reports DESC
""", conn)

reaction_counts.head(20)

         indi_pt                          reaction  reports
0   Colon cancer                             Death      393
1   Colon cancer                           Fatigue      316
2   Colon cancer                         Diarrhoea      285
3   Colon cancer                     Off label use      249
4   Colon cancer                            Nausea      224
5   Colon cancer                      Colon cancer      173
6   Colon cancer                Decreased appetite      171
7   Colon cancer                          Asthenia      153
8   Colon cancer          Blood pressure increased      125
9   Colon cancer                          Vomiting      123
10  Colon cancer             Neuropathy peripheral      119
11  Colon cancer                  Myelosuppression      117
12  Colon cancer                       Neutropenia      113
13  Colon cancer                          Dyspnoea      112
14  Colon cancer                         Dysphonia      101
15  Colon cancer                          Pruritus       97
16  Colon cancer                              Pain       97
17  Colon cancer                    Abdominal pain       96
18  Colon cancer  White blood cell count decreased       92
19  Colon cancer                              Rash       90

In [16]:
ranked_reactions = pd.read_sql_query("""
WITH reaction_counts AS (
    SELECT
        i.indi_pt,
        r.pt AS reaction,
        COUNT(DISTINCT r.primaryid) AS reports
    FROM indi i
    JOIN reac r ON i.primaryid = r.primaryid
    WHERE i.indi_pt IN (
        'Colon cancer',
        'Colorectal cancer',
        'Colorectal cancer metastatic',
        'Colon cancer metastatic',
        'Malignant peritoneal neoplasm',
        'Pseudomyxoma peritonei',
        'Mucinous adenocarcinoma of appendix'
    )
    GROUP BY i.indi_pt, r.pt
),
ranked AS (
    SELECT *,
        RANK() OVER (
            PARTITION BY indi_pt
            ORDER BY reports DESC
        ) AS reaction_rank
    FROM reaction_counts
)
SELECT * FROM ranked
WHERE reaction_rank <= 5
ORDER BY indi_pt, reaction_rank
""", conn)

ranked_reactions

,indi_pt,reaction,reports,reaction_rank
0,Colon cancer,Death,393,1
1,Colon cancer,Fatigue,316,2
2,Colon cancer,Diarrhoea,285,3
3,Colon cancer,Off label use,249,4
4,Colon cancer,Nausea,224,5
5,Colon cancer metastatic,Off label use,48,1
6,Colon cancer metastatic,Fatigue,31,2
7,Colon cancer metastatic,Diarrhoea,29,3
8,Colon cancer metastatic,Neoplasm progression,29,3
9,Colon cancer metastatic,Asthenia,28,5
10,Colon cancer metastatic,Nausea,28,5
11,Colorectal cancer,Off label use,106,1
12,Colorectal cancer,Diarrhoea,84,2
13,Colorectal cancer,Fatigue,59,3
14,Colorectal cancer,Death,54,4
15,Colorectal cancer,Asthenia,51,5
16,Colorectal cancer metastatic,Colorectal cancer metastatic,171,1
17,Colorectal cancer metastatic,Diarrhoea,165,2
18,Colorectal cancer metastatic,Death,123,3
19,Colorectal cancer metastatic,Nausea,112,4
20,Colorectal cancer metastatic,Neutropenia,105,5
21,Malignant peritoneal neoplasm,Nausea,114,1
22,Malignant peritoneal neoplasm,Fatigue,90,2
23,Malignant peritoneal neoplasm,Platelet count decreased,89,3
24,Malignant peritoneal neoplasm,Malignant neoplasm progression,84,4
25,Malignant peritoneal neoplasm,Off label use,73,5
26,Mucinous adenocarcinoma of appendix,Atrial fibrillation,1,1
27,Mucinous adenocarcinoma of appendix,Diarrhoea,1,1
28,Mucinous adenocarcinoma of appendix,Discomfort,1,1
29,Mucinous adenocarcinoma of appendix,Drug ineffective,1,1
30,Mucinous adenocarcinoma of appendix,Hypoaesthesia,1,1
31,Mucinous adenocarcinoma of appendix,Mucosal toxicity,1,1
32,Mucinous adenocarcinoma of appendix,Neuropathy peripheral,1,1
33,Mucinous adenocarcinoma of appendix,Neurotoxicity,1,1
34,Mucinous adenocarcinoma of appendix,Off label use,1,1
35,Mucinous adenocarcinoma of appendix,Pain in extremity,1,1
36,Mucinous adenocarcinoma of appendix,Palmar-plantar erythrodysaesthesia syndrome,1,1
37,Mucinous adenocarcinoma of appendix,Rash,1,1
38,Pseudomyxoma peritonei,Hyperammonaemia,2,1
39,Pseudomyxoma peritonei,Hyperbilirubinaemia,2,1
40,Pseudomyxoma peritonei,Ischaemic hepatitis,2,1
41,Pseudomyxoma peritonei,Off label use,1,4
42,Pseudomyxoma peritonei,Skin necrosis,1,4

In [18]:
drug_name_map = {
    'AVASTIN': 'BEVACIZUMAB',
    'ERBITUX': 'CETUXIMAB',
    'VECTIBIX': 'PANITUMUMAB',
    'LEUCOVORIN CALCIUM': 'LEUCOVORIN',
    'LEVOLEUCOVORIN CALCIUM': 'LEUCOVORIN',
    'IRINOTECAN HYDROCHLORIDE': 'IRINOTECAN',
    'LONSURF': 'TRIFLURIDINE/TIPIRACIL',
    'BRAFTOVI': 'ENCORAFENIB',
    'MEKTOVI': 'BINIMETINIB',
    'STIVARGA': 'REGORAFENIB',
    'ZEJULA': 'NIRAPARIB',
    'KEYTRUDA': 'PEMBROLIZUMAB',
}

cancer_drugs['drugname_normalized'] = cancer_drugs['drugname'].replace(drug_name_map)

cancer_drugs_normalized = (
    cancer_drugs
    .groupby('drugname_normalized')['reports']
    .sum()
    .reset_index()
    .sort_values('reports', ascending=False)
)

cancer_drugs_normalized

       drugname_normalized  reports
18             OXALIPLATIN     1954
11            FLUOROURACIL     1844
14              LEUCOVORIN     1486
4              BEVACIZUMAB     1366
13              IRINOTECAN      996
6             CAPECITABINE      875
7                CETUXIMAB      807
19             PANITUMUMAB      757
12            FRUQUINTINIB      673
23  TRIFLURIDINE/TIPIRACIL      567
10             ENCORAFENIB      416
17             ONDANSETRON      254
8            DEXAMETHASONE      251
16               NIRAPARIB      233
21             REGORAFENIB      220
20           PEMBROLIZUMAB      172
0            ACETAMINOPHEN      166
1               AMLODIPINE      156
9                  ELIQUIS      149
2                  ASPIRIN      146
5              BINIMETINIB      144
22         SODIUM CHLORIDE      137
15              LOPERAMIDE      130
3             ATORVASTATIN      127

In [19]:
drug_reactions_in_cancer = pd.read_sql_query("""
WITH cancer_reports AS (
    SELECT DISTINCT primaryid
    FROM indi
    WHERE indi_pt IN (
        'Colon cancer',
        'Colorectal cancer metastatic',
        'Colorectal cancer',
        'Colon cancer metastatic',
        'Malignant peritoneal neoplasm',
        'Pseudomyxoma peritonei',
        'Mucinous adenocarcinoma of appendix'
    )
),
drug_reaction_counts AS (
    SELECT
        d.drugname,
        r.pt AS reaction,
        COUNT(DISTINCT d.primaryid) AS reports
    FROM drug d
    JOIN reac r ON d.primaryid = r.primaryid
    JOIN cancer_reports cr ON d.primaryid = cr.primaryid
    WHERE d.drugname IN (
        'OXALIPLATIN', 'FLUOROURACIL', 'BEVACIZUMAB', 'AVASTIN',
        'LEUCOVORIN', 'LEUCOVORIN CALCIUM', 'IRINOTECAN',
        'IRINOTECAN HYDROCHLORIDE', 'CAPECITABINE'
    )
    GROUP BY d.drugname, r.pt
),
ranked AS (
    SELECT *,
        RANK() OVER (
            PARTITION BY drugname
            ORDER BY reports DESC
        ) AS reaction_rank
    FROM drug_reaction_counts
)
SELECT * FROM ranked
WHERE reaction_rank <= 5
ORDER BY drugname, reaction_rank
""", conn)

drug_reactions_in_cancer

,drugname,reaction,reports,reaction_rank
0,AVASTIN,Diarrhoea,50,1
1,AVASTIN,Death,44,2
2,AVASTIN,Fatigue,43,3
3,AVASTIN,Disease progression,30,4
4,AVASTIN,Nausea,25,5
5,BEVACIZUMAB,Diarrhoea,89,1
6,BEVACIZUMAB,Neutropenia,87,2
7,BEVACIZUMAB,Colorectal cancer metastatic,84,3
8,BEVACIZUMAB,Nausea,76,4
9,BEVACIZUMAB,Anaemia,65,5
10,CAPECITABINE,Diarrhoea,109,1
11,CAPECITABINE,Nausea,62,2
12,CAPECITABINE,Death,54,3
13,CAPECITABINE,Fatigue,49,4
14,CAPECITABINE,Neutropenia,39,5
15,CAPECITABINE,Palmar-plantar erythrodysaesthesia syndrome,39,5
16,FLUOROURACIL,Diarrhoea,177,1
17,FLUOROURACIL,Neutropenia,164,2
18,FLUOROURACIL,Neuropathy peripheral,112,3
19,FLUOROURACIL,Thrombocytopenia,109,4
20,FLUOROURACIL,Colorectal cancer metastatic,84,5
21,IRINOTECAN,Diarrhoea,99,1
22,IRINOTECAN,Neutropenia,85,2
23,IRINOTECAN,Nausea,58,3
24,IRINOTECAN,Thrombocytopenia,52,4
25,IRINOTECAN,Colorectal cancer metastatic,44,5
26,IRINOTECAN HYDROCHLORIDE,Myelosuppression,44,1
27,IRINOTECAN HYDROCHLORIDE,Diarrhoea,40,2
28,IRINOTECAN HYDROCHLORIDE,Febrile neutropenia,31,3
29,IRINOTECAN HYDROCHLORIDE,Neutropenia,26,4
30,IRINOTECAN HYDROCHLORIDE,Off label use,22,5
31,LEUCOVORIN,Diarrhoea,105,1
32,LEUCOVORIN,Neutropenia,78,2
33,LEUCOVORIN,Neuropathy peripheral,75,3
34,LEUCOVORIN,Colorectal cancer metastatic,73,4
35,LEUCOVORIN,Febrile neutropenia,61,5
36,LEUCOVORIN CALCIUM,Diarrhoea,50,1
37,LEUCOVORIN CALCIUM,Neutropenia,37,2
38,LEUCOVORIN CALCIUM,Acute kidney injury,27,3
39,LEUCOVORIN CALCIUM,Off label use,22,4
40,LEUCOVORIN CALCIUM,Colorectal cancer metastatic,21,5
41,LEUCOVORIN CALCIUM,Disease progression,21,5
42,OXALIPLATIN,Diarrhoea,138,1
43,OXALIPLATIN,Neuropathy peripheral,125,2
44,OXALIPLATIN,Neutropenia,103,3
45,OXALIPLATIN,Nausea,91,4
46,OXALIPLATIN,Thrombocytopenia,86,5

In [20]:
drug_outcomes_in_cancer = pd.read_sql_query("""
WITH cancer_reports AS (
    SELECT DISTINCT primaryid
    FROM indi
    WHERE indi_pt IN (
        'Colon cancer',
        'Colorectal cancer metastatic',
        'Colorectal cancer',
        'Colon cancer metastatic',
        'Malignant peritoneal neoplasm',
        'Pseudomyxoma peritonei',
        'Mucinous adenocarcinoma of appendix'
    )
),
drug_outcome_counts AS (
    SELECT
        d.drugname,
        o.outc_cod AS outcome,
        COUNT(DISTINCT d.primaryid) AS reports
    FROM drug d
    JOIN outc o ON d.primaryid = o.primaryid
    JOIN cancer_reports cr ON d.primaryid = cr.primaryid
    WHERE d.drugname IN (
        'OXALIPLATIN', 'FLUOROURACIL', 'BEVACIZUMAB', 'AVASTIN',
        'LEUCOVORIN', 'LEUCOVORIN CALCIUM', 'IRINOTECAN',
        'IRINOTECAN HYDROCHLORIDE', 'CAPECITABINE'
    )
    GROUP BY d.drugname, o.outc_cod
),
ranked AS (
    SELECT *,
        RANK() OVER (
            PARTITION BY drugname
            ORDER BY reports DESC
        ) AS outcome_rank
    FROM drug_outcome_counts
)
SELECT * FROM ranked
ORDER BY drugname, outcome_rank
""", conn)

drug_outcomes_in_cancer

                    drugname outcome  reports  outcome_rank
0                    AVASTIN      OT      177             1
1                    AVASTIN      DE       94             2
2                    AVASTIN      HO       88             3
3                    AVASTIN      LT        9             4
4                    AVASTIN      DS        6             5
5                BEVACIZUMAB      OT      677             1
6                BEVACIZUMAB      HO      336             2
7                BEVACIZUMAB      DE      122             3
8                BEVACIZUMAB      LT       76             4
9                BEVACIZUMAB      DS        9             5
10              CAPECITABINE      OT      482             1
11              CAPECITABINE      HO      304             2
12              CAPECITABINE      DE       96             3
13              CAPECITABINE      LT       57             4
14              CAPECITABINE      DS        9             5
15              CAPECITABINE      RI        8             6
16              FLUOROURACIL      OT     1232             1
17              FLUOROURACIL      HO      590             2
18              FLUOROURACIL      DE      127             3
19              FLUOROURACIL      LT      119             4
20              FLUOROURACIL      DS       19             5
21              FLUOROURACIL      RI        1             6
22                IRINOTECAN      OT      440             1
23                IRINOTECAN      HO      147             2
24                IRINOTECAN      DE       54             3
25                IRINOTECAN      LT       31             4
26                IRINOTECAN      DS        3             5
27                IRINOTECAN      RI        1             6
28  IRINOTECAN HYDROCHLORIDE      OT      236             1
29  IRINOTECAN HYDROCHLORIDE      HO      154             2
30  IRINOTECAN HYDROCHLORIDE      DE       24             3
31  IRINOTECAN HYDROCHLORIDE      LT       22             4
32  IRINOTECAN HYDROCHLORIDE      DS        9             5
33                LEUCOVORIN      OT      614             1
34                LEUCOVORIN      HO      262             2
35                LEUCOVORIN      DE       72             3
36                LEUCOVORIN      LT       59             4
37                LEUCOVORIN      DS        4             5
38                LEUCOVORIN      RI        2             6
39        LEUCOVORIN CALCIUM      OT      285             1
40        LEUCOVORIN CALCIUM      HO      177             2
41        LEUCOVORIN CALCIUM      DE       40             3
42        LEUCOVORIN CALCIUM      LT       27             4
43        LEUCOVORIN CALCIUM      DS        6             5
44               OXALIPLATIN      OT     1282             1
45               OXALIPLATIN      HO      597             2
46               OXALIPLATIN      LT      190             3
47               OXALIPLATIN      DE      119             4
48               OXALIPLATIN      DS       12             5